import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const poppins = Poppins({weight:['100','200','300','400','500','600','700','800'], subsets: ["latin"] });

export const metadata = {
  title: "MedCare",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme='medcareTheme'>
      <body className={poppins.className}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
